\## Reg no 075

In [1]:
import numpy as np

import pandas as pd

In [2]:
Student = {'Name': ['Bola', 'Loveth', 'Bassey','Dara','Wills', 'Jane', 'chris', 'Cara', 'Smith','Shola'], 
           'Age': [24,23,19,18,21,22,24,26,25,28], 
           'Relationship_Status': ['Single', 'Married', 'Single', 'Divorced', 'Married', 'Single', 'Divorced','Married', 'Single', 'Divorced'],
          'Department':['Biology', 'Biochemistry', 'History', 'Forestry', 'Law', 'Music', 'Mathematics', 'Chemistry', 'Accounting','Insurance']}

In [3]:
Student

{'Name': ['Bola',
  'Loveth',
  'Bassey',
  'Dara',
  'Wills',
  'Jane',
  'chris',
  'Cara',
  'Smith',
  'Shola'],
 'Age': [24, 23, 19, 18, 21, 22, 24, 26, 25, 28],
 'Relationship_Status': ['Single',
  'Married',
  'Single',
  'Divorced',
  'Married',
  'Single',
  'Divorced',
  'Married',
  'Single',
  'Divorced'],
 'Department': ['Biology',
  'Biochemistry',
  'History',
  'Forestry',
  'Law',
  'Music',
  'Mathematics',
  'Chemistry',
  'Accounting',
  'Insurance']}

In [4]:
Student['CGPA']= [3.1, 4.2, 3.9, 1.8, 2.9, 3.8, 4.5, 4.8, 2.2, 1.5 ]

In [5]:
Student

{'Name': ['Bola',
  'Loveth',
  'Bassey',
  'Dara',
  'Wills',
  'Jane',
  'chris',
  'Cara',
  'Smith',
  'Shola'],
 'Age': [24, 23, 19, 18, 21, 22, 24, 26, 25, 28],
 'Relationship_Status': ['Single',
  'Married',
  'Single',
  'Divorced',
  'Married',
  'Single',
  'Divorced',
  'Married',
  'Single',
  'Divorced'],
 'Department': ['Biology',
  'Biochemistry',
  'History',
  'Forestry',
  'Law',
  'Music',
  'Mathematics',
  'Chemistry',
  'Accounting',
  'Insurance'],
 'CGPA': [3.1, 4.2, 3.9, 1.8, 2.9, 3.8, 4.5, 4.8, 2.2, 1.5]}

In [5]:
Student.pop('Relationship_Status')

['Single',
 'Married',
 'Single',
 'Divorced',
 'Married',
 'Single',
 'Divorced',
 'Married',
 'Single',
 'Divorced']

In [6]:
Student

{'Name': ['Bola',
  'Loveth',
  'Bassey',
  'Dara',
  'Wills',
  'Jane',
  'chris',
  'Cara',
  'Smith',
  'Shola'],
 'Age': [24, 23, 19, 18, 21, 22, 24, 26, 25, 28],
 'Department': ['Biology',
  'Biochemistry',
  'History',
  'Forestry',
  'Law',
  'Music',
  'Mathematics',
  'Chemistry',
  'Accounting',
  'Insurance'],
 'CGPA': [3.1, 4.2, 3.9, 1.8, 2.9, 3.8, 4.5, 4.8, 2.2, 1.5]}

In [7]:
df = pd.DataFrame(Student)

In [8]:
df

Name  Age    Department  CGPA
0    Bola   24       Biology   3.1
1  Loveth   23  Biochemistry   4.2
2  Bassey   19       History   3.9
3    Dara   18      Forestry   1.8
4   Wills   21           Law   2.9
5    Jane   22         Music   3.8
6   chris   24   Mathematics   4.5
7    Cara   26     Chemistry   4.8
8   Smith   25    Accounting   2.2
9   Shola   28     Insurance   1.5

In [9]:
df['Admission_date']= '2021-9-14', '2019-9-12', '2018-9-19', '2021-9-1', '2017-9-5', '2016-9-9', '2019-9-2', '2020-9-28', '2020-9-16', '2017-9-13'
df['Gender'] = 'Male', 'Female', 'Male', 'Female' ,'Male', 'Female' ,'Male', 'Female', 'Male', 'Female'

In [10]:
df

Name  Age    Department  CGPA Admission_date  Gender
0    Bola   24       Biology   3.1      2021-9-14    Male
1  Loveth   23  Biochemistry   4.2      2019-9-12  Female
2  Bassey   19       History   3.9      2018-9-19    Male
3    Dara   18      Forestry   1.8       2021-9-1  Female
4   Wills   21           Law   2.9       2017-9-5    Male
5    Jane   22         Music   3.8       2016-9-9  Female
6   chris   24   Mathematics   4.5       2019-9-2    Male
7    Cara   26     Chemistry   4.8      2020-9-28  Female
8   Smith   25    Accounting   2.2      2020-9-16    Male
9   Shola   28     Insurance   1.5      2017-9-13  Female

In [11]:
name =['Tunde', 'Kate', 'Bassey','Ada','Wills', 'Jane', 'chris', 'Etim', 'Smith','Karen'] 

age = [24,23,19,18,21,22,24,26,25,28]

department = ['Biology', 'Biochemistry', 'History', 'Forestry', 'Law', 'Music', 'Mathematics', 'Chemistry', 'Accounting','Insurance']

admission_date= ['2021-9-14', '2019-9-12', '2018-9-19', '2021-9-1', '2017-9-5', '2016-9-9', '2019-9-2', '2020-9-28', '2020-9-16', '2017-9-13']

gender = ['Male', 'Female', 'Male', 'Female' ,'Male', 'Female' ,'Male', 'Female', 'Male', 'Female']


df2=pd.DataFrame({'Name':name, 'Age':age, 'Department':department, 'Gender':gender,'Admission_date':admission_date})

In [12]:
df2

Name  Age    Department  Gender Admission_date
0   Tunde   24       Biology    Male      2021-9-14
1    Kate   23  Biochemistry  Female      2019-9-12
2  Bassey   19       History    Male      2018-9-19
3     Ada   18      Forestry  Female       2021-9-1
4   Wills   21           Law    Male       2017-9-5
5    Jane   22         Music  Female       2016-9-9
6   chris   24   Mathematics    Male       2019-9-2
7    Etim   26     Chemistry  Female      2020-9-28
8   Smith   25    Accounting    Male      2020-9-16
9   Karen   28     Insurance  Female      2017-9-13

In [16]:
import datetime as dt

In [20]:
df['Admission_date'] = pd.to_datetime (df['Admission_date'])

In [21]:
df

Name  Age    Department  CGPA Admission_date  Gender
0    Bola   24       Biology   3.1     2021-09-14    Male
1  Loveth   23  Biochemistry   4.2     2019-09-12  Female
2  Bassey   19       History   3.9     2018-09-19    Male
3    Dara   18      Forestry   1.8     2021-09-01  Female
4   Wills   21           Law   2.9     2017-09-05    Male
5    Jane   22         Music   3.8     2016-09-09  Female
6   chris   24   Mathematics   4.5     2019-09-02    Male
7    Cara   26     Chemistry   4.8     2020-09-28  Female
8   Smith   25    Accounting   2.2     2020-09-16    Male
9   Shola   28     Insurance   1.5     2017-09-13  Female

In [23]:
df['year'] =(df['Admission_date']).dt.year

In [24]:
df

Name  Age    Department  CGPA Admission_date  Gender  year
0    Bola   24       Biology   3.1     2021-09-14    Male  2021
1  Loveth   23  Biochemistry   4.2     2019-09-12  Female  2019
2  Bassey   19       History   3.9     2018-09-19    Male  2018
3    Dara   18      Forestry   1.8     2021-09-01  Female  2021
4   Wills   21           Law   2.9     2017-09-05    Male  2017
5    Jane   22         Music   3.8     2016-09-09  Female  2016
6   chris   24   Mathematics   4.5     2019-09-02    Male  2019
7    Cara   26     Chemistry   4.8     2020-09-28  Female  2020
8   Smith   25    Accounting   2.2     2020-09-16    Male  2020
9   Shola   28     Insurance   1.5     2017-09-13  Female  2017

In [26]:
df['month'] = (df['Admission_date']).dt.month

In [27]:
df

Name  Age    Department  CGPA Admission_date  Gender  year  month
0    Bola   24       Biology   3.1     2021-09-14    Male  2021      9
1  Loveth   23  Biochemistry   4.2     2019-09-12  Female  2019      9
2  Bassey   19       History   3.9     2018-09-19    Male  2018      9
3    Dara   18      Forestry   1.8     2021-09-01  Female  2021      9
4   Wills   21           Law   2.9     2017-09-05    Male  2017      9
5    Jane   22         Music   3.8     2016-09-09  Female  2016      9
6   chris   24   Mathematics   4.5     2019-09-02    Male  2019      9
7    Cara   26     Chemistry   4.8     2020-09-28  Female  2020      9
8   Smith   25    Accounting   2.2     2020-09-16    Male  2020      9
9   Shola   28     Insurance   1.5     2017-09-13  Female  2017      9

In [28]:
df['day']=(df['Admission_date']).dt.day

In [29]:
df

Name  Age    Department  CGPA Admission_date  Gender  year  month  day
0    Bola   24       Biology   3.1     2021-09-14    Male  2021      9   14
1  Loveth   23  Biochemistry   4.2     2019-09-12  Female  2019      9   12
2  Bassey   19       History   3.9     2018-09-19    Male  2018      9   19
3    Dara   18      Forestry   1.8     2021-09-01  Female  2021      9    1
4   Wills   21           Law   2.9     2017-09-05    Male  2017      9    5
5    Jane   22         Music   3.8     2016-09-09  Female  2016      9    9
6   chris   24   Mathematics   4.5     2019-09-02    Male  2019      9    2
7    Cara   26     Chemistry   4.8     2020-09-28  Female  2020      9   28
8   Smith   25    Accounting   2.2     2020-09-16    Male  2020      9   16
9   Shola   28     Insurance   1.5     2017-09-13  Female  2017      9   13

In [30]:
df.dtypes

Name                      object
Age                        int64
Department                object
CGPA                     float64
Admission_date    datetime64[ns]
Gender                    object
year                       int64
month                      int64
day                        int64
dtype: object

In [33]:
df.isna()

Name    Age  Department   CGPA  Admission_date  Gender   year  month  \
0  False  False       False  False           False   False  False  False   
1  False  False       False  False           False   False  False  False   
2  False  False       False  False           False   False  False  False   
3  False  False       False  False           False   False  False  False   
4  False  False       False  False           False   False  False  False   
5  False  False       False  False           False   False  False  False   
6  False  False       False  False           False   False  False  False   
7  False  False       False  False           False   False  False  False   
8  False  False       False  False           False   False  False  False   
9  False  False       False  False           False   False  False  False   

     day  
0  False  
1  False  
2  False  
3  False  
4  False  
5  False  
6  False  
7  False  
8  False  
9  False

In [35]:
df.isnull().sum()*100/len(df)

Name              0.0
Age               0.0
Department        0.0
CGPA              0.0
Admission_date    0.0
Gender            0.0
year              0.0
month             0.0
day               0.0
dtype: float64

In [38]:
df.Name.unique()

array(['Bola', 'Loveth', 'Bassey', 'Dara', 'Wills', 'Jane', 'chris',
       'Cara', 'Smith', 'Shola'], dtype=object)

In [39]:
df.Age.unique()

array([24, 23, 19, 18, 21, 22, 26, 25, 28], dtype=int64)

In [40]:
df.Department.unique()

array(['Biology', 'Biochemistry', 'History', 'Forestry', 'Law', 'Music',
       'Mathematics', 'Chemistry', 'Accounting', 'Insurance'],
      dtype=object)

In [42]:
df.CGPA.unique()

array([3.1, 4.2, 3.9, 1.8, 2.9, 3.8, 4.5, 4.8, 2.2, 1.5])

In [43]:
df.Admission_date.unique()

array(['2021-09-14T00:00:00.000000000', '2019-09-12T00:00:00.000000000',
       '2018-09-19T00:00:00.000000000', '2021-09-01T00:00:00.000000000',
       '2017-09-05T00:00:00.000000000', '2016-09-09T00:00:00.000000000',
       '2019-09-02T00:00:00.000000000', '2020-09-28T00:00:00.000000000',
       '2020-09-16T00:00:00.000000000', '2017-09-13T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [44]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [45]:
df.year.unique()

array([2021, 2019, 2018, 2017, 2016, 2020], dtype=int64)

In [46]:
df.month.unique()

array([9], dtype=int64)

In [47]:
df.day.unique()

array([14, 12, 19,  1,  5,  9,  2, 28, 16, 13], dtype=int64)

In [49]:
df.Name.nunique()

10

In [50]:
df.Age.nunique()

9

In [51]:
df.Department.nunique()

10

In [54]:
df.Admission_date.nunique()

10

In [ ]:
df.CGPA.unique()

In [53]:
df.Gender.nunique()

2

In [55]:
df.year.nunique()

6

In [56]:
df.month.nunique()

1

In [57]:
df.day.nunique()

10

In [58]:
df.Name.value_counts()

Bola      1
Loveth    1
Bassey    1
Dara      1
Wills     1
Jane      1
chris     1
Cara      1
Smith     1
Shola     1
Name: Name, dtype: int64

In [59]:
df.Age.value_counts()

24    2
23    1
19    1
18    1
21    1
22    1
26    1
25    1
28    1
Name: Age, dtype: int64

In [60]:
df.Department.value_counts()

Biology         1
Biochemistry    1
History         1
Forestry        1
Law             1
Music           1
Mathematics     1
Chemistry       1
Accounting      1
Insurance       1
Name: Department, dtype: int64

In [61]:
df.CGPA.value_counts()

3.1    1
4.2    1
3.9    1
1.8    1
2.9    1
3.8    1
4.5    1
4.8    1
2.2    1
1.5    1
Name: CGPA, dtype: int64

In [62]:
df.Admission_date.value_counts()

2021-09-14    1
2019-09-12    1
2018-09-19    1
2021-09-01    1
2017-09-05    1
2016-09-09    1
2019-09-02    1
2020-09-28    1
2020-09-16    1
2017-09-13    1
Name: Admission_date, dtype: int64

In [63]:
df.Gender.value_counts()

Male      5
Female    5
Name: Gender, dtype: int64

In [64]:
df.year.value_counts()

2021    2
2019    2
2017    2
2020    2
2018    1
2016    1
Name: year, dtype: int64

In [65]:
df.month.value_counts()

9    10
Name: month, dtype: int64

In [66]:
df.day.value_counts()

14    1
12    1
19    1
1     1
5     1
9     1
2     1
28    1
16    1
13    1
Name: day, dtype: int64

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Name            10 non-null     object        
 1   Age             10 non-null     int64         
 2   Department      10 non-null     object        
 3   CGPA            10 non-null     float64       
 4   Admission_date  10 non-null     datetime64[ns]
 5   Gender          10 non-null     object        
 6   year            10 non-null     int64         
 7   month           10 non-null     int64         
 8   day             10 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 848.0+ bytes


In [68]:
df.describe()

Age       CGPA        year  month        day
count  10.000000  10.000000    10.00000   10.0  10.000000
mean   23.000000   3.270000  2018.80000    9.0  11.900000
std     3.091206   1.154749     1.75119    0.0   8.198238
min    18.000000   1.500000  2016.00000    9.0   1.000000
25%    21.250000   2.375000  2017.25000    9.0   6.000000
50%    23.500000   3.450000  2019.00000    9.0  12.500000
75%    24.750000   4.125000  2020.00000    9.0  15.500000
max    28.000000   4.800000  2021.00000    9.0  28.000000

In [69]:
df.describe().T

count     mean       std     min       25%      50%       75%     max
Age     10.0    23.00  3.091206    18.0    21.250    23.50    24.750    28.0
CGPA    10.0     3.27  1.154749     1.5     2.375     3.45     4.125     4.8
year    10.0  2018.80  1.751190  2016.0  2017.250  2019.00  2020.000  2021.0
month   10.0     9.00  0.000000     9.0     9.000     9.00     9.000     9.0
day     10.0    11.90  8.198238     1.0     6.000    12.50    15.500    28.0

In [72]:
df.shape[0]

10

In [73]:
df.shape[1]

9

In [83]:
df.query('Gender == "Male"')

Name  Age   Department  CGPA Admission_date Gender  year  month  day
0    Bola   24      Biology   3.1     2021-09-14   Male  2021      9   14
2  Bassey   19      History   3.9     2018-09-19   Male  2018      9   19
4   Wills   21          Law   2.9     2017-09-05   Male  2017      9    5
6   chris   24  Mathematics   4.5     2019-09-02   Male  2019      9    2
8   Smith   25   Accounting   2.2     2020-09-16   Male  2020      9   16

In [92]:
df['CGPA'].max(axis=0)

4.8

In [93]:
df['CGPA'].min(axis=0)

1.5

In [94]:
df['CGPA'].mean(axis=0)

3.2700000000000005

In [95]:
df['CGPA'].sum(axis=0)

32.7

In [96]:
df

Name  Age    Department  CGPA Admission_date  Gender  year  month  day
0    Bola   24       Biology   3.1     2021-09-14    Male  2021      9   14
1  Loveth   23  Biochemistry   4.2     2019-09-12  Female  2019      9   12
2  Bassey   19       History   3.9     2018-09-19    Male  2018      9   19
3    Dara   18      Forestry   1.8     2021-09-01  Female  2021      9    1
4   Wills   21           Law   2.9     2017-09-05    Male  2017      9    5
5    Jane   22         Music   3.8     2016-09-09  Female  2016      9    9
6   chris   24   Mathematics   4.5     2019-09-02    Male  2019      9    2
7    Cara   26     Chemistry   4.8     2020-09-28  Female  2020      9   28
8   Smith   25    Accounting   2.2     2020-09-16    Male  2020      9   16
9   Shola   28     Insurance   1.5     2017-09-13  Female  2017      9   13

In [98]:
 df.to_csv('df.csv',index = False)